version: '2'

services:
   web:
     image: ebuzaneli/nginx-php7 
     hostname: buzza-server-nginx
     container_name: buzza-server-nginx
     ports: 
       - "8080:80"
     volumes:
       - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-Lemp-PHP-7.0/www:/app
       - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-Lemp-PHP-7.0/php/php.ini:/etc/php/7.0/fpm/php.ini
     links:
       - db
     restart: always
     depends_on:
       - db
     networks:
        - buzza-protocolo-network
          

   db:
      image: ebuzaneli/buzza-server-mysql:5.6
      hostname: buzza-server-mysql
      container_name: buzza-server-mysql
      ports:
         - "3307:3306"
      volumes:
         - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-Lemp-PHP-7.0/mysql-data:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=123456
         - MYSQL_DATABASE=db_buzza
         - TZ=America/Campo_Grande
      restart: always
      networks:
        - buzza-protocolo-network

   phpmyadmin:
      image: ebuzaneli/buzza-phpmyadmin:latest 
      hostname: buzza-server-phpmyadmin
      container_name: buzza-server-phpmyadmin
      links:
         - db
      environment:
         PMA_HOST: db
         PMA_PORT: 3306
      ports:
         - '8082:80' 
      restart: always
      depends_on:
        - db
      networks:
        - buzza-protocolo-network


   ssh:
      image: ebuzaneli/buzza-server-ssh:latest 
      hostname: buzza-server-ssh
      container_name: buzza-server-ssh
      environment:
         - "SSH_USER=buzza"
         - "SSH_PASSWORD=102030" 
         - TZ=America/Campo_Grande
      volumes:
         - /Users/eniomarcelobuzaneli/Documents/Docker/Docker-Lemp-PHP-7.0/www:/var/www/html
      ports:
         - '2222:22'
      restart: always
      networks:
        - buzza-protocolo-network



networks:
  buzza-protocolo-network:
    driver: bridge
